name: Playwright Tests
on:
  workflow_call:
  pull_request:
    branches: ['main']
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        e2e:
          [
            { browser: 'chromium', project: 'desktop chromium' },
            { browser: 'firefox', project: 'desktop firefox' },
            { browser: 'webkit', project: 'desktop webkit' },
            { browser: 'chromium', project: 'mobile chromium' },
            { browser: 'webkit', project: 'mobile safari' },
          ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ matrix.e2e.browser }}
      - name: Run Playwright tests
        run: npx playwright test --project="${{ matrix.e2e.project }}"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.e2e.project }}
          path: playwright-report/
          retention-days: 7
